spring:
  profiles:
    active: dev
  data: 
    redis:
      database: 0  
      host: ${REDIS_HOST}
      port: 6379  
      password: ${REDIS_PWD}
      jedis:
        pool:
          max-active: 8  
          max-wait: -1
          max-idle: 8  
          min-idle: 0  
      timeout: 0
---
spring:
  config:
    activate:
      on-profile: prod
niq:
  tw:
    api:
      url: https://api.niq.tw
---
spring:
  config:
    activate:
      on-profile: dev
niq:
  tw:
    api:
      url: http://localhost:8080
server:
  port: 8888
logging.level:
  '[org.springframework.security]': debug
